export const GET_MOVIES_BEGIN="GET_MOVIES_BEGIN";
export const GET_MOVIES_SUCCESS="GET_MOVIES_SUCCESS";
export const HANDLE_CHANGE="HANDLE_CHANGE";

export const SETUP_USER_BEGIN='SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS='SETUP_USER_SUCCESS';

export const REMOVE_USER_BEGIN='REMOVE_USER_BEGIN';
export const REMOVE_USER_SUCCESS='REMOVE_USER_SUCCESS';
